window.PORTFOLIO_SETTINGS = {
  editorPassword: "yopassword",
  contentVersion: "frelerr-style-v10",
  discordClientId: "1500899174512591129",
  recaptchaSiteKey: ""
};

window.PORTFOLIO_DATA = {
  contact: {
    email: "frelerrlele@gmail.com",
    links: [
      {
        label: "YouTube",
        url: "https://www.youtube.com/@frelerr"
      },
      {
        label: "Twitch",
        url: "https://www.twitch.tv/itsfrelerr"
      }
    ]
  },
  translations: {
    it: {
      siteName: "Home",
      languageLabel: "Lingua",
      navWork: "Progetti",
      navAbout: "Info",
      navContact: "Link",
      eyebrow: "Portfolio di Frelerr",
      headline: "Frelerr",
      intro: "Ciao, sono Frelerr. Qui raccolgo video, social, esperimenti e commissioni.",
      ctaWork: "Guarda",
      ctaContact: "Link",
      statCategories: "Categorie",
      availabilityLabel: "Status",
      availability: "Aperto a commissioni",
      workEyebrow: "Progetti",
      workTitle: "Cose che sto facendo o che voglio mostrare.",
      filterAll: "Tutto",
      openProject: "Apri",
      catCazzeggio: "Cazzeggio",
      catSocialmedia: "Social media",
      catCommissioni: "Commissioni",
      noImage: "Non ancora messo",
      aboutEyebrow: "Chi sono",
      aboutTitle: "Faccio contenuti, esperimenti e lavori su richiesta.",
      aboutText: "Questa pagina raccoglie i miei canali, i miei progetti e le commissioni. Tengo tutto qui, semplice e diretto.",
      contactEyebrow: "Link",
      contactTitle: "Mi trovi qui.",
      loginButton: "Accedi",
      loginDiscord: "Accedi con Discord",
      loginGoogle: "Accedi con Google",
      loginEmail: "Accedi con Email",
      loginLogout: "Esci",
      authEyebrow: "Accesso",
      authTitle: "Crea il tuo profilo",
      authEmailLabel: "Email",
      authPasswordLabel: "Password",
      authUsernameLabel: "Nome utente",
      authPhotoLabel: "Foto profilo",
      authCaptcha: "Verifica reCAPTCHA",
      authHint: "Gli account vengono registrati nel database locale del server Node.",
      authSubmit: "Entra",
      authCancel: "Annulla",
      authPhotoHelp: "Clicca il cerchio per caricare una foto.",
      authCaptchaMissing: "Aggiungi una site key reCAPTCHA in content.js per attivare la verifica reale.",
      authEmailInvalid: "Inserisci una email reale, non di prova.",
      authCaptchaInvalid: "Completa la verifica reCAPTCHA.",
      authEmailHelp: "Inserisci una E-Mail valida",
      authPasswordHelp: "Minimo 6 caratteri",
      authUsernameHelp: "Non inserire il tuo vero Nome",
      passwordWeak: "Password debole",
      passwordMedium: "Password media",
      passwordStrong: "Password sicura",
      authServerError: "Avvia il server locale per registrare account reali."
    },
    de: {
      siteName: "Home",
      languageLabel: "Sprache",
      navWork: "Projekte",
      navAbout: "Info",
      navContact: "Links",
      eyebrow: "Portfolio von Frelerr",
      headline: "Frelerr",
      intro: "Hi, ich bin Frelerr. Hier sammle ich Videos, Socials, Experimente und Auftraege.",
      ctaWork: "Ansehen",
      ctaContact: "Links",
      statCategories: "Kategorien",
      availabilityLabel: "Status",
      availability: "Offen fuer Auftraege",
      workEyebrow: "Projekte",
      workTitle: "Dinge, an denen ich arbeite oder die ich zeigen will.",
      filterAll: "Alles",
      openProject: "Oeffnen",
      catCazzeggio: "Spielerei",
      catSocialmedia: "Social Media",
      catCommissioni: "Auftraege",
      noImage: "Noch nicht eingefuegt",
      aboutEyebrow: "Info",
      aboutTitle: "Ich mache Content, Experimente und Arbeiten auf Anfrage.",
      aboutText: "Diese Seite sammelt meine Kanaele, meine Projekte und Auftraege. Alles bleibt hier einfach und direkt.",
      contactEyebrow: "Links",
      contactTitle: "Meine Links.",
      loginButton: "Login",
      loginDiscord: "Mit Discord einloggen",
      loginGoogle: "Mit Google einloggen",
      loginEmail: "Mit Email einloggen",
      loginLogout: "Abmelden",
      authEyebrow: "Login",
      authTitle: "Erstelle dein Profil",
      authEmailLabel: "Email",
      authPasswordLabel: "Passwort",
      authUsernameLabel: "Benutzername",
      authPhotoLabel: "Profilbild",
      authCaptcha: "reCAPTCHA bestaetigen",
      authHint: "Lokaler Demo-Login: fuer echten Login braucht es ein Backend.",
      authSubmit: "Einloggen",
      authCancel: "Abbrechen",
      authPhotoHelp: "Klicke auf den Kreis, um ein Profilbild hochzuladen.",
      authCaptchaMissing: "Fuege in content.js einen reCAPTCHA Site Key ein, um echte Verifizierung zu aktivieren.",
      authEmailInvalid: "Gib eine echte Email ein, keine Test-Adresse.",
      authCaptchaInvalid: "Schliesse die reCAPTCHA Verifizierung ab."
    },
    en: {
      siteName: "Home",
      languageLabel: "Language",
      navWork: "Projects",
      navAbout: "Info",
      navContact: "Links",
      eyebrow: "Frelerr portfolio",
      headline: "Frelerr",
      intro: "Hi, I am Frelerr. I collect my videos, socials, experiments, and commissions here.",
      ctaWork: "View",
      ctaContact: "Links",
      statCategories: "Categories",
      availabilityLabel: "Status",
      availability: "Open for commissions",
      workEyebrow: "Projects",
      workTitle: "Things I am making or want to show.",
      filterAll: "All",
      openProject: "Open",
      catCazzeggio: "Playground",
      catSocialmedia: "Social media",
      catCommissioni: "Commissions",
      noImage: "Not added yet",
      aboutEyebrow: "About",
      aboutTitle: "I make content, experiments, and work on request.",
      aboutText: "This page collects my channels, my projects, and commissions. I keep everything here, simple and direct.",
      contactEyebrow: "Links",
      contactTitle: "Find me here.",
      loginButton: "Log in",
      loginDiscord: "Log in with Discord",
      loginGoogle: "Log in with Google",
      loginEmail: "Log in with Email",
      loginLogout: "Log out",
      authEyebrow: "Login",
      authTitle: "Create your profile",
      authEmailLabel: "Email",
      authPasswordLabel: "Password",
      authUsernameLabel: "Username",
      authPhotoLabel: "Profile photo",
      authCaptcha: "Verify reCAPTCHA",
      authHint: "Local demo login: a real login needs a backend.",
      authSubmit: "Enter",
      authCancel: "Cancel",
      authPhotoHelp: "Click the circle to upload a photo.",
      authCaptchaMissing: "Add a reCAPTCHA site key in content.js to enable real verification.",
      authEmailInvalid: "Enter a real email, not a test address.",
      authCaptchaInvalid: "Complete the reCAPTCHA verification."
    },
    es: {
      siteName: "Home",
      languageLabel: "Idioma",
      navWork: "Proyectos",
      navAbout: "Info",
      navContact: "Links",
      eyebrow: "Portfolio de Frelerr",
      headline: "Frelerr",
      intro: "Hola, soy Frelerr. Aquí junto videos, redes, experimentos y comisiones.",
      ctaWork: "Ver",
      ctaContact: "Links",
      statCategories: "Categorías",
      availabilityLabel: "Estado",
      availability: "Abierto a comisiones",
      workEyebrow: "Proyectos",
      workTitle: "Cosas que estoy haciendo o que quiero mostrar.",
      filterAll: "Todo",
      openProject: "Abrir",
      catCazzeggio: "Extras",
      catSocialmedia: "Redes",
      catCommissioni: "Comisiones",
      noImage: "Aún no añadido",
      aboutEyebrow: "Sobre mí",
      aboutTitle: "Hago contenido, experimentos y trabajos por encargo.",
      aboutText: "Esta página reúne mis canales, mis proyectos y las comisiones. Todo queda simple y directo.",
      contactEyebrow: "Links",
      contactTitle: "Me encuentras aquí.",
      loginButton: "Entrar",
      loginDiscord: "Entrar con Discord",
      loginGoogle: "Entrar con Google",
      loginEmail: "Entrar con Email",
      loginLogout: "Salir",
      authEyebrow: "Acceso",
      authTitle: "Crea tu perfil",
      authEmailLabel: "Email",
      authPasswordLabel: "Contraseña",
      authUsernameLabel: "Nombre de usuario",
      authPhotoLabel: "Foto de perfil",
      authCaptcha: "Verifica reCAPTCHA",
      authHint: "Acceso local de demostración: para hacerlo real hace falta un backend.",
      authSubmit: "Entrar",
      authCancel: "Cancelar",
      authPhotoHelp: "Haz clic en el círculo para subir una foto.",
      authCaptchaMissing: "Añade una site key de reCAPTCHA en content.js para activar la verificación real.",
      authEmailInvalid: "Introduce un email real, no una dirección de prueba.",
      authCaptchaInvalid: "Completa la verificación reCAPTCHA."
    },
    fr: {
      siteName: "Home",
      languageLabel: "Langue",
      navWork: "Projets",
      navAbout: "Info",
      navContact: "Liens",
      eyebrow: "Portfolio de Frelerr",
      headline: "Frelerr",
      intro: "Salut, je suis Frelerr. Je rassemble ici mes vidéos, réseaux, essais et commissions.",
      ctaWork: "Voir",
      ctaContact: "Liens",
      statCategories: "Catégories",
      availabilityLabel: "Statut",
      availability: "Ouvert aux commissions",
      workEyebrow: "Projets",
      workTitle: "Ce que je crée ou ce que je veux montrer.",
      filterAll: "Tout",
      openProject: "Ouvrir",
      catCazzeggio: "Extras",
      catSocialmedia: "Réseaux",
      catCommissioni: "Commissions",
      noImage: "Pas encore ajouté",
      aboutEyebrow: "À propos",
      aboutTitle: "Je fais du contenu, des essais et des travaux sur demande.",
      aboutText: "Cette page rassemble mes chaînes, mes projets et les commissions. Je garde tout simple et direct.",
      contactEyebrow: "Liens",
      contactTitle: "Tu me trouves ici.",
      loginButton: "Connexion",
      loginDiscord: "Connexion avec Discord",
      loginGoogle: "Connexion avec Google",
      loginEmail: "Connexion avec Email",
      loginLogout: "Déconnexion",
      authEyebrow: "Connexion",
      authTitle: "Crée ton profil",
      authEmailLabel: "Email",
      authPasswordLabel: "Mot de passe",
      authUsernameLabel: "Nom d'utilisateur",
      authPhotoLabel: "Photo de profil",
      authCaptcha: "Vérifie reCAPTCHA",
      authHint: "Connexion locale de démonstration : il faut un backend pour une vraie connexion.",
      authSubmit: "Entrer",
      authCancel: "Annuler",
      authPhotoHelp: "Clique sur le cercle pour importer une photo.",
      authCaptchaMissing: "Ajoute une site key reCAPTCHA dans content.js pour activer la vraie vérification.",
      authEmailInvalid: "Entre une vraie adresse email, pas une adresse de test.",
      authCaptchaInvalid: "Complète la vérification reCAPTCHA."
    },
    ru: {
      siteName: "Home",
      languageLabel: "Язык",
      navWork: "Проекты",
      navAbout: "Инфо",
      navContact: "Ссылки",
      eyebrow: "Портфолио Frelerr",
      headline: "Frelerr",
      intro: "Привет, я Frelerr. Здесь собраны видео, соцсети, эксперименты и заказы.",
      ctaWork: "Смотреть",
      ctaContact: "Ссылки",
      statCategories: "Категории",
      availabilityLabel: "Статус",
      availability: "Открыт для заказов",
      workEyebrow: "Проекты",
      workTitle: "То, что я делаю или хочу показать.",
      filterAll: "Все",
      openProject: "Открыть",
      catCazzeggio: "Экстра",
      catSocialmedia: "Соцсети",
      catCommissioni: "Заказы",
      noImage: "Еще не добавлено",
      aboutEyebrow: "Обо мне",
      aboutTitle: "Я делаю контент, эксперименты и работы на заказ.",
      aboutText: "На этой странице собраны мои каналы, проекты и заказы. Все просто и по делу.",
      contactEyebrow: "Ссылки",
      contactTitle: "Меня можно найти здесь.",
      loginButton: "Войти",
      loginDiscord: "Войти через Discord",
      loginGoogle: "Войти через Google",
      loginEmail: "Войти через Email",
      loginLogout: "Выйти",
      authEyebrow: "Вход",
      authTitle: "Создай профиль",
      authEmailLabel: "Email",
      authPasswordLabel: "Пароль",
      authUsernameLabel: "Имя пользователя",
      authPhotoLabel: "Фото профиля",
      authCaptcha: "Подтверди reCAPTCHA",
      authHint: "Локальный демо-вход: для настоящего входа нужен backend.",
      authSubmit: "Войти",
      authCancel: "Отмена",
      authPhotoHelp: "Нажми на круг, чтобы загрузить фото.",
      authCaptchaMissing: "Добавь site key reCAPTCHA в content.js, чтобы включить настоящую проверку.",
      authEmailInvalid: "Введи реальный email, а не тестовый адрес.",
      authCaptchaInvalid: "Заверши проверку reCAPTCHA."
    }
  },
  projects: [
    {
      id: "extra",
      category: "cazzeggio",
      accent: "#d90028",
      year: "2026",
      url: "#",
      image: "",
      placeholder: "#6d38d8",
      title: {
        it: "Extra",
        de: "Extras",
        en: "Extras",
        es: "Extras",
        fr: "Extras",
        ru: "Экстра"
      },
      tags: ["test", "idee", "random"],
      description: {
        it: "Qui metto idee libere, test, cose random e contenuti piu leggeri.",
        de: "Freie Ideen, Tests, random Sachen und leichtere Inhalte.",
        en: "Loose ideas, tests, random things, and lighter content I want to show.",
        es: "Ideas libres, pruebas, cosas random y contenido más ligero.",
        fr: "Des idées libres, des tests, des choses random et du contenu plus léger.",
        ru: "Свободные идеи, тесты, случайные штуки и более легкий контент."
      }
    },
    {
      id: "youtube-social",
      category: "socialmedia",
      accent: "#ff2d3f",
      year: "2026",
      url: "https://www.youtube.com/@frelerr",
      image: "",
      placeholder: "#7d3cc4",
      title: {
        it: "YouTube e social",
        de: "YouTube und Socials",
        en: "YouTube and socials",
        es: "YouTube y redes",
        fr: "YouTube et réseaux",
        ru: "YouTube и соцсети"
      },
      tags: ["video", "reel", "social"],
      description: {
        it: "Video, post, reel e contenuti collegati ai miei canali.",
        de: "Videos, Posts, Reels und Inhalte rund um meine Kanaele.",
        en: "Videos, posts, reels, and content connected to my channels.",
        es: "Videos, posts, reels y contenido conectado con mis canales.",
        fr: "Vidéos, posts, reels et contenus liés à mes chaînes.",
        ru: "Видео, посты, рилсы и контент, связанный с моими каналами."
      }
    },
    {
      id: "commissioni",
      category: "commissioni",
      accent: "#b60022",
      year: "2026",
      url: "#",
      image: "",
      placeholder: "#5533b3",
      title: {
        it: "Commissioni",
        de: "Auftraege",
        en: "Commissions",
        es: "Comisiones",
        fr: "Commissions",
        ru: "Заказы"
      },
      tags: ["grafiche", "pagine", "contenuti"],
      description: {
        it: "Qui metto lavori richiesti da altre persone, grafiche, pagine o contenuti.",
        de: "Hier zeige ich Arbeiten fuer andere Personen, Grafiken, Seiten oder Content.",
        en: "Requested work, graphics, pages, or content I made for other people.",
        es: "Trabajos pedidos por otras personas, gráficos, páginas o contenido.",
        fr: "Travaux demandés par d'autres personnes, graphismes, pages ou contenu.",
        ru: "Работы по запросу других людей: графика, страницы или контент."
      }
    }
  ]
};
